### ISSUE TITLE
Add option to add MOS badge on Roster

### ISSUE THREAD

**Issue by Holidayy95** [forumify/forumify-perscom-plugin#10]
Would be nice to add a little image on this part of the roster, to show their specific MOS

https://i.imgur.com/VNIzSpV.png

example of where to add it would be in the image above. If not Image entry, just ignore and collapse the space there like it is currently without.

**Comment by jannes-io** [comment]
Hi @Holidayy95 ,

Thanks for the suggestion, we would love to display more badges and iconography on the roster and in other places, but unfortunately PERSCOM.io does not currently give users an option to upload an image on specialties.

![image](https://github.com/user-attachments/assets/0c470806-fe8a-43bb-9028-4581f91e12c4)

Feel free to re-open or recreate this issue when PERSCOM.io has this data available in their API.
