### ISSUE TITLE
Add automations for service records

### ISSUE THREAD

**Issue by Holidayy95** [forumify/forumify-perscom-plugin#12]
Example; you could have it so every X days/X months, you could add a specific defined entry. This is based on their Time in service.

So 6 Months/180 Days add an entry for '6 Months Time in Service'

**Comment by jannes-io** [comment]
Hi @Holidayy95 ,

Thanks for the suggestion. At this point in time we believe that this feature belongs on PERSCOM.io and not in the PERSCOM plugin for forumify.

We are planning to build a premium "PERSCOM enhanced" plugin in the future that brings back many beloved features and additional automation that is currently missing from PERSCOM.io.

If PERSCOM.io does not provide this functionality by the time we get to that feature, we will revisit this suggestion.
